// AB Omar - Drive Backup V4 - نهائي بدون 404
const AB_OMAR_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbyV8WQb8MIN3Dxfc7IBBXIYjgza-xFq6p_ujvu66z_95mcfvr4t5ZpAXRzAZbdkCDgC/exec";
let isBackingUp = false;
let autoBackupTimer = null;
function getAllDataForBackup(){return {daily:JSON.parse(localStorage.getItem('omar_tx_v3')||'[]'),attendance:JSON.parse(localStorage.getItem('att_fixed_final')||'{}'),attendance_log:JSON.parse(localStorage.getItem('attendance_log')||'[]'),tasks:JSON.parse(localStorage.getItem('tasks_v6')||'[]'),important:JSON.parse(localStorage.getItem('omar_important')||'[]'),debts:JSON.parse(localStorage.getItem('debts_pro_v2')||'[]'),backup_date:new Date().toISOString()}}
async function backupToDrive(showAlert=true){if(isBackingUp) return false;isBackingUp=true;let payload=getAllDataForBackup();try{if(showAlert) console.log('☁ جاري النسخ للدرايف...');await fetch(AB_OMAR_APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify(payload)});localStorage.setItem('ab_omar_last_backup',new Date().toISOString());if(showAlert){console.log('✅ تم النسخ للدرايف بنجاح');if(window.showToast) showToast('✅ تم الحفظ على Drive');}else{console.log('✅ Synced to Drive:',(payload.tasks||[]).length,'tasks | من',new Date().toLocaleTimeString());}return true;}catch(err){console.warn('Backup failed:',err.message);if(showAlert) alert('فشل النسخ: '+err.message);return false;}finally{isBackingUp=false;}}
async function restoreFromDrive(){if(!confirm('هل تريد استرجاع النسخة من Google Drive؟ سيتم استبدال البيانات الحالية.')) return;try{let res=await fetch(AB_OMAR_APPS_SCRIPT_URL+'?t='+Date.now(),{method:'GET',redirect:'follow',cache:'no-store'});let text=await res.text();let data=JSON.parse(text);if(data.error){alert('لا يوجد نسخة: '+data.error);return;}if(data.daily) localStorage.setItem('omar_tx_v3',JSON.stringify(data.daily));if(data.tasks) localStorage.setItem('tasks_v6',JSON.stringify(data.tasks));if(data.attendance) localStorage.setItem('att_fixed_final',JSON.stringify(data.attendance));if(data.attendance_log) localStorage.setItem('attendance_log',JSON.stringify(data.attendance_log));if(data.important) localStorage.setItem('omar_important',JSON.stringify(data.important));if(data.debts) localStorage.setItem('debts_pro_v2',JSON.stringify(data.debts));alert('✅ تم الاسترجاع بنجاح - سيتم تحديث الصفحة');location.reload();}catch(err){alert('فشل الاسترجاع: '+err.message+'\n\nافتح الرابط ده مباشرة وشوف الداتا: '+AB_OMAR_APPS_SCRIPT_URL);}}
function requestAutoBackup(){if(autoBackupTimer) clearTimeout(autoBackupTimer);autoBackupTimer=setTimeout(()=>{backupToDrive(false);},4000);}
(function(){const keysToWatch=['omar_tx_v3','tasks_v6','att_fixed_final','attendance_log','omar_important','debts_pro_v2'];const originalSetItem=localStorage.setItem;localStorage.setItem=function(k,v){originalSetItem.apply(this,arguments);if(keysToWatch.includes(k)){requestAutoBackup();}};})();
window.addEventListener('load',()=>{let hasData=localStorage.getItem('omar_tx_v3')||localStorage.getItem('tasks_v6');if(!hasData){console.log('لا يوجد داتا محلية، محاولة استرجاع تلقائي...');setTimeout(async()=>{try{let res=await fetch(AB_OMAR_APPS_SCRIPT_URL+'?t='+Date.now(),{cache:'no-store'});let data=await res.json();if(!data.error&&data.daily){if(confirm('وجدنا نسخة محفوظة على Drive، هل تريد استرجاعها؟')){localStorage.setItem('omar_tx_v3',JSON.stringify(data.daily||[]));localStorage.setItem('tasks_v6',JSON.stringify(data.tasks||[]));localStorage.setItem('att_fixed_final',JSON.stringify(data.attendance||{}));localStorage.setItem('attendance_log',JSON.stringify(data.attendance_log||[]));localStorage.setItem('omar_important',JSON.stringify(data.important||[]));localStorage.setItem('debts_pro_v2',JSON.stringify(data.debts||[]));location.reload();}}}catch(e){}},2000);}});
function exportToExcel(){let data=getAllDataForBackup();function toCSV(rows){return rows.map(r=>r.map(c=>'"'+String(c||'').replace(/"/g,'""')+'"').join(',')).join('\n');}let dailyRows=[['النوع','البند','الشخص','المبلغ','التاريخ','المحفظة','ملاحظة']];(data.daily||[]).forEach(t=>{dailyRows.push([t.type||'',t.item||'',t.person||'',t.amount||'',t.date||'',t.wallet||'',(t.note||'').replace(/,/g,' ')]);});let taskRows=[['النص','التصنيف','منجز','اللون','ملاحظة']];(data.tasks||[]).forEach(t=>{taskRows.push([t.text||'',t.cat||'',t.done?'نعم':'لا',t.color||'',(t.note||'').replace(/<[^>]*>/g,' ').substring(0,150)]);});let csvContent='\ufeffاليومية\n'+toCSV(dailyRows)+'\n\nالمهام\n'+toCSV(taskRows);let blob=new Blob([csvContent],{type:'text/csv;charset=utf-8;'});let url=URL.createObjectURL(blob);let a=document.createElement('a');a.href=url;a.download='AB_Omar_Export_'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(url);}
function exportFullJSON(){let data=getAllDataForBackup();let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let url=URL.createObjectURL(blob);let a=document.createElement('a');a.href=url;a.download='AB_Omar_FullBackup_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(url);}
window.backupToDrive=backupToDrive;window.restoreFromDrive=restoreFromDrive;window.exportToExcel=exportToExcel;window.exportFullJSON=exportFullJSON;window.getAllDataForBackup=getAllDataForBackup;
console.log('✅ AB Omar Backup Ready V4 - تلقائي هادي كل 4 ثواني بعد التغيير');
